//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int CertificateId { get; set; }
        public int TemplateId { get; set; }
        public int ResidentId { get; set; }
        public System.DateTime DateIssued { get; set; }
        public string CertificateContent { get; set; }
        public string OfficialReceiptNum { get; set; }
        public string TaxCertificateNum { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual LetterTemplate LetterTemplate { get; set; }
        public virtual Resident Resident { get; set; }
    }
}
