//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateCommunity
    {
        public int TaxCertificateId { get; set; }
        public int CCI { get; set; }
        public int Year { get; set; }
        public string PlaceIssued { get; set; }
        public System.DateTime DateIssued { get; set; }
        public int ResidentId { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<decimal> BasicCommunityTax { get; set; }
        public Nullable<decimal> BusinessEarningsTax { get; set; }
        public Nullable<decimal> ProfessionalEarningsTax { get; set; }
        public Nullable<decimal> PropertyEarningsTax { get; set; }
        public Nullable<int> Interest { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    
        public virtual Resident Resident { get; set; }
    }
}
