//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clearance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clearance()
        {
            this.MaintenanceTables = new HashSet<MaintenanceTable>();
        }
    
        public int ClearanceId { get; set; }
        public int ResidentId { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public string CTC { get; set; }
        public System.DateTime CTCDate { get; set; }
        public string CTCPlaceIssued { get; set; }
        public string ORNumber { get; set; }
        public Nullable<int> YearsOfStay { get; set; }
        public string Comelec { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Resident Resident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceTable> MaintenanceTables { get; set; }
    }
}
