//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaint()
        {
            this.ResidentRespondents = new HashSet<Resident>();
            this.ResidentComplainants = new HashSet<Resident>();
            this.ResidentVictims = new HashSet<Resident>();
            this.Settlements = new HashSet<Settlement>();
        }
    
        public int ComplaintId { get; set; }
        public string ComplaintTitle { get; set; }
        public string NonResidentComplainants { get; set; }
        public string NonResidentRespondents { get; set; }
        public string NonResidentVictims { get; set; }
        public string IncidentLocation { get; set; }
        public int DisputeNature { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public System.DateTime DateTimeRecorded { get; set; }
        public string ComplainantNarrative { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public int ModeOfSettlement { get; set; }
        public int ComplaintStatus { get; set; }
        public Nullable<decimal> GovernmentSavings { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resident> ResidentRespondents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resident> ResidentComplainants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resident> ResidentVictims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settlement> Settlements { get; set; }
        public virtual MaintenanceTable Dispute { get; set; }
        public virtual MaintenanceTable Status { get; set; }
        public virtual MaintenanceTable SettlementMode { get; set; }
    }
}
