//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomLog
    {
        public int EventId { get; set; }
        public string JsonData { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string EventType { get; set; }
        public string ByUser { get; set; }
    }
}
