//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisasterRelocationSite
    {
        public int DisasterRelocationSiteId { get; set; }
        public int DisasterId { get; set; }
        public string DisasterRelocationSiteName { get; set; }
        public string DisasterRelocationSiteDesc { get; set; }
        public string DisasterRelocationSiteAddress { get; set; }
        public string DisasterRelocationSiteCapacity { get; set; }
        public string DisasterRelocationSiteContactPerson { get; set; }
        public string DisasterRelocationSiteContactNumber { get; set; }
    
        public virtual Disaster Disaster { get; set; }
    }
}
