//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisasterStatus
    {
        public int DisasterStatusId { get; set; }
        public int DisasterId { get; set; }
        public System.DateTime DisasterStatusDateTime { get; set; }
        public int DisasterLevel { get; set; }
        public string DisasterStatusDesc { get; set; }
        public string SmsMessage { get; set; }
    
        public virtual Disaster Disaster { get; set; }
    }
}
