//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseholdPropertyProduction
    {
        public int HouseholdProductionId { get; set; }
        public int MaintenanceId { get; set; }
        public int Quantity { get; set; }
        public int HouseholdId { get; set; }
    
        public virtual MaintenanceTable MaintenanceTable { get; set; }
        public virtual Household Household { get; set; }
    }
}
