//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrgyMgmt.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resident()
        {
            this.ComplaintRespondents = new HashSet<Complaint>();
            this.ComplaintComplainants = new HashSet<Complaint>();
            this.ComplaintVictims = new HashSet<Complaint>();
            this.CertificateCommunities = new HashSet<CertificateCommunity>();
            this.Certificates = new HashSet<Certificate>();
            this.Clearances = new HashSet<Clearance>();
        }
    
        public int ResidentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Alias { get; set; }
        public string Cellular { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
        public int HouseHoldId { get; set; }
        public byte[] BiometricCapture { get; set; }
        public string FullName { get; set; }
        public bool HouseholdHead { get; set; }
        public Nullable<int> RelToHouseholdHead { get; set; }
        public bool Disability { get; set; }
        public string DisabilityKind { get; set; }
        public Nullable<bool> HasDisabilityCard { get; set; }
        public bool PPPP { get; set; }
        public Nullable<int> PPPPYear { get; set; }
        public bool isVoter { get; set; }
        public string VoteRegistrationLoc { get; set; }
        public Nullable<int> ResidenceYears { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string CivilStatus { get; set; }
        public int EthnicityId { get; set; }
        public int ReligionId { get; set; }
        public int EducationalAttainmentId { get; set; }
        public int EducationStatus { get; set; }
        public string FamilyMemberSpecialNeeds { get; set; }
        public string Occupation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> ComplaintRespondents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> ComplaintComplainants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> ComplaintVictims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificateCommunity> CertificateCommunities { get; set; }
        public virtual Household Household { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificate> Certificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clearance> Clearances { get; set; }
    }
}
